name: business_tracker
description: A complete business sales and expense tracking app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  firebase_core: ^2.15.0
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.9.0
  sqflite: ^2.3.0
  path: ^1.8.3
  syncfusion_flutter_pdf: ^23.1.0
  syncfusion_flutter_datagrid: ^23.1.0
  syncfusion_flutter_charts: ^23.1.0
  charts_flutter: ^0.12.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^16.3.0
  permission_handler: ^11.0.1
  file_picker: ^5.5.0
  open_file: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
